spring.application.name=firstapp
# Use Wildcard "*" to expose all endpoints
# We can also expose individual endpoints with a comma-delimited list
management.endpoints.web.exposure.include=*
management.info.env.enabled=true

# Exclude individual endpoints with a comma-delimited list
# management.endpoints.web.exposure.exclude=info, health

info.app.name=My first Application
info.app.description= This is my first app in Spring Boot but will not be the last one!
info.app.version= 1.0.0

#
# Define my properties
#
coach.name= Juergen Klopp
team.name= BVB Dortmund

#
# change Spring Boot embedded server port
#
server.port=7070

#
# Set the context path of the application
#
# all requests should be prefixed with /firstapp
#
server.servlet.context-path=/firstapp
