spring.application.name=firstapp
# Use Wildcard "*" to expose all endpoints
# We can also expose individual endpoints with a comma-delimited list
management.endpoints.web.exposure.include=*
management.info.env.enabled=true
info.app.name=My first Application
info.app.description= This is my first app in Spring Boot but will not be the last one!
info.app.version= 1.0.0